apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: rule-evaluation-engine
    app.kubernetes.io/instance: observatorium-xyz
    app.kubernetes.io/name: thanos-rule
    app.kubernetes.io/part-of: observatorium
    app.kubernetes.io/version: v0.17.1
  name: observatorium-xyz-thanos-rule
  namespace: observatorium
