apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: jaeger-agent
  name: jaeger-agent
  namespace: observatorium
spec:
  ports:
  - name: metrics
    port: 14271
    targetPort: 14271
  selector:
    app.kubernetes.io/tracing: jaeger-agent
