apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    endpoint: federate
    k8s-app: telemeter-server
  name: telemeter-server-federate
  namespace: observatorium
spec:
  endpoints:
  - honorLabels: true
    interval: 15s
    params:
      match[]:
      - '{__name__=~".*"}'
    path: /federate
    port: internal
    scheme: http
  jobLabel: k8s-app
  selector:
    matchLabels:
      k8s-app: telemeter-server
