apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: telemeter-server-shared
  labels:
    k8s-app: telemeter-server
  name: telemeter-server
  namespace: observatorium
spec:
  clusterIP: None
  ports:
  - name: external
    port: 8080
    targetPort: external
  - name: internal
    port: 8081
    targetPort: internal
  - name: cluster
    port: 8082
    targetPort: cluster
  selector:
    k8s-app: telemeter-server
