apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: memcached
  name: memcached
  namespace: observatorium
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: memcached
  serviceName: memcached
  template:
    metadata:
      labels:
        app.kubernetes.io/name: memcached
    spec:
      containers:
      - args:
        - -m 1024
        - -I 1m
        - -c 1024
        - -v
        image: docker.io/memcached:1.5.20-alpine
        name: memcached
        ports:
        - containerPort: 11211
          name: client
        resources:
          limits:
            cpu: "3"
            memory: 1844Mi
          requests:
            cpu: 500m
            memory: 1329Mi
      - args:
        - --memcached.address=localhost:11211
        - --web.listen-address=0.0.0.0:9150
        image: docker.io/prom/memcached-exporter:v0.6.0
        name: exporter
        ports:
        - containerPort: 9150
          name: metrics
