apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: thanos-receive-controller
  name: thanos-receive-controller
  namespace: observatorium
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: thanos-receive-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: thanos-receive-controller
    spec:
      containers:
      - args:
        - --configmap-name=observatorium-tenants
        - --configmap-generated-name=observatorium-tenants-generated
        - --file-name=hashrings.json
        - --namespace=$(NAMESPACE)
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: quay.io/observatorium/thanos-receive-controller:master-2019-08-08-61eeaf0
        name: thanos-receive-controller
      serviceAccount: thanos-receive-controller
