apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: app-sre
    role: alert-rules
  name: observatorium-thanos-stage
spec:
  groups:
  - name: thanos-compact.rules
    rules:
    - alert: ThanosCompactMultipleCompactsAreRunning
      annotations:
        message: You should never run more than one Thanos Compact at once. You have
          {{ $value }}
      expr: sum(up{job=~"thanos-compactor.*", namespace="telemeter-stage"}) > 1
      for: 5m
      labels:
        severity: warning
    - alert: ThanosCompactHalted
      annotations:
        message: Thanos Compact {{$labels.job}} has failed to run and now is halted.
      expr: thanos_compactor_halted{job=~"thanos-compactor.*", namespace="telemeter-stage"}
        == 1
      for: 5m
      labels:
        severity: warning
    - alert: ThanosCompactHighCompactionFailures
      annotations:
        message: Thanos Compact {{$labels.job}} is failing to execute {{ $value |
          humanize }}% of compactions.
      expr: |
        (
          sum by (job) (rate(thanos_compact_group_compactions_failures_total{job=~"thanos-compactor.*", namespace="telemeter-stage"}[5m]))
        /
          sum by (job) (rate(thanos_compact_group_compactions_total{job=~"thanos-compactor.*", namespace="telemeter-stage"}[5m]))
        * 100 > 5
        )
      for: 15m
      labels:
        severity: warning
    - alert: ThanosCompactBucketHighOperationFailures
      annotations:
        message: Thanos Compact {{$labels.job}} Bucket is failing to execute {{ $value
          | humanize }}% of operations.
      expr: |
        (
          sum by (job) (rate(thanos_objstore_bucket_operation_failures_total{job=~"thanos-compactor.*", namespace="telemeter-stage"}[5m]))
        /
          sum by (job) (rate(thanos_objstore_bucket_operations_total{job=~"thanos-compactor.*", namespace="telemeter-stage"}[5m]))
        * 100 > 5
        )
      for: 15m
      labels:
        severity: warning
    - alert: ThanosCompactHasNotRun
      annotations:
        message: Thanos Compact {{$labels.job}} has not uploaded anything for 24 hours.
      expr: (time() - max(thanos_objstore_bucket_last_successful_upload_time{job=~"thanos-compactor.*",
        namespace="telemeter-stage"})) / 60 / 60 > 24
      labels:
        severity: warning
  - name: thanos-querier.rules
    rules:
    - alert: ThanosQuerierGrpcServerErrorRate
      annotations:
        message: Thanos Querier {{$labels.job}} is failing to handle {{ $value | humanize
          }}% of requests.
      expr: |
        (
          sum by (job) (rate(grpc_server_handled_total{grpc_code=~"Unknown|ResourceExhausted|Internal|Unavailable", job=~"thanos-querier.*", namespace="telemeter-stage"}[5m]))
        /
          sum by (job) (rate(grpc_server_started_total{job=~"thanos-querier.*", namespace="telemeter-stage"}[5m]))
        * 100 > 5
        )
      for: 5m
      labels:
        severity: warning
    - alert: ThanosQuerierGrpcClientErrorRate
      annotations:
        message: Thanos Querier {{$labels.job}} is failing to send {{ $value | humanize
          }}% of requests.
      expr: |
        (
          sum by (job) (rate(grpc_client_handled_total{grpc_code!="OK", job=~"thanos-querier.*", namespace="telemeter-stage"}[5m]))
        /
          sum by (job) (rate(grpc_client_started_total{job=~"thanos-querier.*", namespace="telemeter-stage"}[5m]))
        * 100 > 5
        )
      for: 5m
      labels:
        severity: warning
    - alert: ThanosQuerierHighDNSFailures
      annotations:
        message: Thanos Queriers {{$labels.job}} have {{ $value }} of failing DNS
          queries.
      expr: |
        (
          sum by (job) (rate(thanos_querier_store_apis_dns_failures_total{job=~"thanos-querier.*", namespace="telemeter-stage"}[5m]))
        /
          sum by (job) (rate(thanos_querier_store_apis_dns_lookups_total{job=~"thanos-querier.*", namespace="telemeter-stage"}[5m]))
        > 1
        )
      for: 15m
      labels:
        severity: warning
    - alert: ThanosQuerierInstantLatencyHigh
      annotations:
        message: Thanos Querier {{$labels.job}} has a 99th percentile latency of {{
          $value }} seconds for instant queries.
      expr: |
        (
          histogram_quantile(0.99, sum by (job, le) (http_request_duration_seconds_bucket{job=~"thanos-querier.*", namespace="telemeter-stage", handler="query"})) > 10
        and
          sum by (job) (rate(http_request_duration_seconds_bucket{job=~"thanos-querier.*", namespace="telemeter-stage", handler="query"}[5m])) > 0
        )
      for: 10m
      labels:
        severity: critical
    - alert: ThanosQuerierRangeLatencyHigh
      annotations:
        message: Thanos Querier {{$labels.job}} has a 99th percentile latency of {{
          $value }} seconds for instant queries.
      expr: |
        (
          histogram_quantile(0.99, sum by (job, le) (http_request_duration_seconds_bucket{job=~"thanos-querier.*", namespace="telemeter-stage", handler="query_range"})) > 10
        and
          sum by (job) (rate(http_request_duration_seconds_count{job=~"thanos-querier.*", namespace="telemeter-stage", handler="query_range"}[5m])) > 0
        )
      for: 10m
      labels:
        severity: critical
  - name: thanos-receive.rules
    rules:
    - alert: ThanosReceiveHttpRequestLatencyHigh
      annotations:
        message: Thanos Receive {{$labels.job}} has a 99th percentile latency of {{
          $value }} seconds for HTTP requests.
      expr: |
        (
          histogram_quantile(0.99, sum by (job, le) (http_request_duration_seconds_bucket{job=~"thanos-receive.*", namespace="telemeter-stage", handler="receive"})) > 10
        and
          sum by (job) (rate(http_request_duration_seconds_count{job=~"thanos-receive.*", namespace="telemeter-stage", handler="receive"}[5m])) > 0
        )
      for: 10m
      labels:
        severity: critical
    - alert: ThanosReceiveHighForwardRequestFailures
      annotations:
        message: Thanos Receive {{$labels.job}} is failing to forward {{ $value |
          humanize }}% of requests.
      expr: |
        (
          sum by (job) (rate(thanos_receive_forward_requests_total{result="error", job=~"thanos-receive.*", namespace="telemeter-stage"}[5m]))
        /
          sum by (job) (rate(thanos_receive_forward_requests_total{job=~"thanos-receive.*", namespace="telemeter-stage"}[5m]))
        * 100 > 5
        )
      for: 15m
      labels:
        severity: critical
    - alert: ThanosReceiveHighHashringFileRefreshFailures
      annotations:
        message: Thanos Receive {{$labels.job}} is failing to refresh hashring file,
          {{ $value | humanize }} of attempts failed.
      expr: |
        (
          sum by (job) (rate(thanos_receive_hashrings_file_errors_total{job=~"thanos-receive.*", namespace="telemeter-stage"}[5m]))
        /
          sum by (job) (rate(thanos_receive_hashrings_file_refreshes_total{job=~"thanos-receive.*", namespace="telemeter-stage"}[5m]))
        > 0
        )
      for: 15m
      labels:
        severity: warning
    - alert: ThanosReceiveConfigReloadFailure
      annotations:
        message: Thanos Receive {{$labels.job}} has not been able to reload hashring
          configurations.
      expr: avg(thanos_receive_config_last_reload_successful{job=~"thanos-receive.*",
        namespace="telemeter-stage"}) by (job) != 1
      for: 5m
      labels:
        severity: warning
  - name: thanos-store.rules
    rules:
    - alert: ThanosStoreGrpcErrorRate
      annotations:
        message: Thanos Store {{$labels.job}} is failing to handle {{ $value | humanize
          }}% of requests.
      expr: |
        (
          sum by (job) (rate(grpc_server_handled_total{grpc_code=~"Unknown|ResourceExhausted|Internal|Unavailable", job=~"thanos-store.*", namespace="telemeter-stage"}[5m]))
        /
          sum by (job) (rate(grpc_server_started_total{job=~"thanos-store.*", namespace="telemeter-stage"}[5m]))
        * 100 > 5
        )
      for: 5m
      labels:
        severity: warning
    - alert: ThanosStoreSeriesGateLatencyHigh
      annotations:
        message: Thanos Store {{$labels.job}} has a 99th percentile latency of {{
          $value }} seconds for store series gate requests.
      expr: |
        (
          histogram_quantile(0.99, sum by (job, le) (thanos_bucket_store_series_gate_duration_seconds_bucket{job=~"thanos-store.*", namespace="telemeter-stage"})) > 2
        and
          sum by (job) (rate(thanos_bucket_store_series_gate_duration_seconds_count{job=~"thanos-store.*", namespace="telemeter-stage"}[5m])) > 0
        )
      for: 10m
      labels:
        severity: warning
    - alert: ThanosStoreBucketHighOperationFailures
      annotations:
        message: Thanos Store {{$labels.job}} Bucket is failing to execute {{ $value
          | humanize }}% of operations.
      expr: |
        (
          sum by (job) (rate(thanos_objstore_bucket_operation_failures_total{job=~"thanos-store.*", namespace="telemeter-stage"}[5m]))
        /
          sum by (job) (rate(thanos_objstore_bucket_operations_total{job=~"thanos-store.*", namespace="telemeter-stage"}[5m]))
        * 100 > 5
        )
      for: 15m
      labels:
        severity: warning
    - alert: ThanosStoreObjstoreOperationLatencyHigh
      annotations:
        message: Thanos Store {{$labels.job}} Bucket has a 99th percentile latency
          of {{ $value }} seconds for the bucket operations.
      expr: |
        (
          histogram_quantile(0.99, sum by (job, le) (thanos_objstore_bucket_operation_duration_seconds_bucket{job=~"thanos-store.*", namespace="telemeter-stage"})) > 15
        and
          sum by (job) (rate(thanos_objstore_bucket_operation_duration_seconds_count{job=~"thanos-store.*", namespace="telemeter-stage"}[5m]))) > 0
        )
      for: 10m
      labels:
        severity: warning
  - name: thanos-component-absent
    rules:
    - alert: ThanosCompactIsDown
      annotations:
        message: ThanosCompact has disappeared from Prometheus target discovery.
      expr: |
        absent(up{job=~"thanos-compactor.*", namespace="telemeter-stage"} == 1)
      for: 10m
      labels:
        severity: critical
    - alert: ThanosQuerierIsDown
      annotations:
        message: ThanosQuerier has disappeared from Prometheus target discovery.
      expr: |
        absent(up{job=~"thanos-querier.*", namespace="telemeter-stage"} == 1)
      for: 10m
      labels:
        severity: critical
    - alert: ThanosReceiveIsDown
      annotations:
        message: ThanosReceive has disappeared from Prometheus target discovery.
      expr: |
        absent(up{job=~"thanos-receive.*", namespace="telemeter-stage"} == 1)
      for: 10m
      labels:
        severity: critical
    - alert: ThanosStoreIsDown
      annotations:
        message: ThanosStore has disappeared from Prometheus target discovery.
      expr: |
        absent(up{job=~"thanos-store.*", namespace="telemeter-stage"} == 1)
      for: 10m
      labels:
        severity: critical
  - name: thanos-receive-controller.rules
    rules:
    - alert: ThanosReceiveControllerReconcileErrorRate
      annotations:
        message: Thanos Receive Controller failing to reconcile changes, {{ $value
          | humanize }}% of attempts failed.
      expr: |
        sum(
          rate(thanos_receive_controller_reconcile_errors_total{job=~"thanos-receive-controller.*",namespace="telemeter-stage"}[5m])
          /
          on (namespace) group_left
          rate(thanos_receive_controller_reconcile_attempts_total{job=~"thanos-receive-controller.*",namespace="telemeter-stage"}[5m])
        ) * 100 >= 10
      for: 5m
      labels:
        severity: warning
    - alert: ThanosReceiveControllerConfigmapChangeErrorRate
      annotations:
        message: Thanos Receive Controller failing to refresh configmap, {{ $value
          | humanize }}% of attempts failed.
      expr: |
        sum(
          rate(thanos_receive_controller_configmap_change_errors_total{job=~"thanos-receive-controller.*",namespace="telemeter-stage"}[5m])
          /
          on (namespace) group_left
          rate(thanos_receive_controller_configmap_change_attempts_total{job=~"thanos-receive-controller.*",namespace="telemeter-stage"}[5m])
        ) * 100 >= 10
      for: 5m
      labels:
        severity: warning
    - alert: ThanosReceiveConfigInconsistent
      annotations:
        message: The configuration of the instances of Thanos Receive `{{$labels.job}}`
          are out of sync.
      expr: |
        avg(thanos_receive_config_hash{job=~"thanos-receive.*", namespace="telemeter-stage"}) BY (namespace, job)
          /
        on (namespace)
        group_left
        thanos_receive_controller_configmap_hash{job=~"thanos-receive-controller.*",namespace="telemeter-stage"}
        != 1
      for: 5m
      labels:
        severity: critical
