apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: kubernetes-controller
    app.kubernetes.io/instance: observatorium-xyz
    app.kubernetes.io/name: thanos-receive-controller
    app.kubernetes.io/part-of: observatorium
    app.kubernetes.io/version: master-2020-02-06-b66e0c8
  name: observatorium-xyz-thanos-receive-controller
  namespace: observatorium
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: kubernetes-controller
      app.kubernetes.io/instance: observatorium-xyz
      app.kubernetes.io/name: thanos-receive-controller
      app.kubernetes.io/part-of: observatorium
  template:
    metadata:
      labels:
        app.kubernetes.io/component: kubernetes-controller
        app.kubernetes.io/instance: observatorium-xyz
        app.kubernetes.io/name: thanos-receive-controller
        app.kubernetes.io/part-of: observatorium
        app.kubernetes.io/version: master-2020-02-06-b66e0c8
    spec:
      containers:
      - args:
        - --configmap-name=observatorium-xyz-thanos-receive-controller-tenants
        - --configmap-generated-name=observatorium-xyz-thanos-receive-controller-tenants-generated
        - --file-name=hashrings.json
        - --namespace=$(NAMESPACE)
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: quay.io/observatorium/thanos-receive-controller:master-2020-02-06-b66e0c8
        name: thanos-receive-controller
        ports:
        - containerPort: 8080
          name: http
      serviceAccount: observatorium-xyz-thanos-receive-controller
