apiVersion: core.observatorium.io/v1alpha1
kind: Observatorium
metadata:
  app.kubernetes.io/component: observatorium-cr
  app.kubernetes.io/instance: observatorium-xyz
  app.kubernetes.io/name: observatorium-cr
  app.kubernetes.io/part-of: observatorium
  name: observatorium-xyz
spec:
  apiGateway:
    image: quay.io/observatorium/observatorium:HEAD-2020-04-16-v0.1.0
    version: HEAD-2020-04-16-v0.1.0
  compact:
    retentionResolution1h: 1s
    retentionResolution5m: 1s
    retentionResolutionRaw: 14d
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
  hashrings:
  - hashring: default
    tenants: []
  objectStorageConfig:
    key: thanos.yaml
    name: thanos-objectstorage
  queryCache:
    image: quay.io/cortexproject/cortex:master-fdcd992f
    replicas: 1
    version: master-fdcd992f
  receivers:
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
  rule:
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
  store:
    shards: 1
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
  thanosImage: quay.io/thanos/thanos:v0.12.0-rc.1
  thanosReceiveController:
    image: quay.io/observatorium/thanos-receive-controller:master-2020-02-06-b66e0c8
    version: master-2020-02-06-b66e0c8
  thanosVersion: v0.12.0-rc.1
