apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: api-gateway
    app.kubernetes.io/instance: observatorium-xyz
    app.kubernetes.io/name: observatorium-api-gateway
    app.kubernetes.io/part-of: observatorium
    app.kubernetes.io/version: master-2020-01-28-e009b4a
  name: observatorium-xyz-observatorium-api-gateway
  namespace: observatorium
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/component: api-gateway
    app.kubernetes.io/instance: observatorium-xyz
    app.kubernetes.io/name: observatorium-api-gateway
    app.kubernetes.io/part-of: observatorium
