apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: observatorium-xyz
    app.kubernetes.io/name: observatorium-api
    app.kubernetes.io/part-of: observatorium
    app.kubernetes.io/version: master-2020-10-23-v0.1.1-180-g7c57706
  name: observatorium-xyz-observatorium-api
  namespace: observatorium
stringData:
  tenants.yaml: |-
    "tenants":
    - "id": "1610b0c3-c509-4592-a256-a1871353dbfa"
      "name": "test"
      "oidc":
        "clientID": "test"
        "clientSecret": "ZXhhbXBsZS1hcHAtc2VjcmV0"
        "issuerURL": "http://dex.dex.svc.cluster.local:5556/dex"
        "usernameClaim": "email"
