apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: identity-provider
    app.kubernetes.io/instance: e2e-test
    app.kubernetes.io/name: dex
    app.kubernetes.io/version: v2.24.0
  name: dex
  namespace: dex
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: identity-provider
      app.kubernetes.io/instance: e2e-test
      app.kubernetes.io/name: dex
      app.kubernetes.io/version: v2.24.0
  template:
    metadata:
      labels:
        app.kubernetes.io/component: identity-provider
        app.kubernetes.io/instance: e2e-test
        app.kubernetes.io/name: dex
        app.kubernetes.io/version: v2.24.0
    spec:
      containers:
      - command:
        - /usr/local/bin/dex
        - serve
        - /etc/dex/cfg/config.yaml
        image: quay.io/dexidp/dex:v2.24.0
        name: dex
        ports:
        - containerPort: 5556
          name: http
        volumeMounts:
        - mountPath: /etc/dex/cfg
          name: config
        - mountPath: /storage
          name: storage
          readOnly: false
      volumes:
      - name: config
        secret:
          items:
          - key: config.yaml
            path: config.yaml
          secretName: dex
      - name: storage
        persistentVolumeClaim:
          claimName: dex
