apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: table-manager
    app.kubernetes.io/instance: observatorium-xyz
    app.kubernetes.io/name: loki
    app.kubernetes.io/part-of: observatorium
    app.kubernetes.io/version: 1.6.1
  name: observatorium-xyz-loki-table-manager
  namespace: observatorium
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: table-manager
      app.kubernetes.io/instance: observatorium-xyz
      app.kubernetes.io/name: loki
      app.kubernetes.io/part-of: observatorium
  template:
    metadata:
      labels:
        app.kubernetes.io/component: table-manager
        app.kubernetes.io/instance: observatorium-xyz
        app.kubernetes.io/name: loki
        app.kubernetes.io/part-of: observatorium
    spec:
      containers:
      - args:
        - -target=table-manager
        - -config.file=/etc/loki/config/config.yaml
        - -limits.per-user-override-config=/etc/loki/config/overrides.yaml
        - -s3.url=$(S3_URL)
        - -s3.force-path-style=true
        - -log.level=error
        env:
        - name: S3_URL
          valueFrom:
            secretKeyRef:
              key: endpoint
              name: loki-objectstorage
        image: docker.io/grafana/loki:1.6.1
        name: observatorium-xyz-loki-table-manager
        ports:
        - containerPort: 3100
          name: metrics
        - containerPort: 9095
          name: grpc
        readinessProbe:
          httpGet:
            path: /ready
            port: 3100
            scheme: HTTP
          initialDelaySeconds: 15
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 100Mi
        volumeMounts:
        - mountPath: /etc/loki/config/
          name: config
          readOnly: false
        - mountPath: /data
          name: storage
          readOnly: false
      volumes:
      - configMap:
          name: observatorium-xyz-loki
        name: config
      - emptyDir: {}
        name: storage
