apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: distributor
    app.kubernetes.io/instance: observatorium-xyz
    app.kubernetes.io/name: loki
    app.kubernetes.io/part-of: observatorium
    app.kubernetes.io/version: 1.6.1
  name: observatorium-xyz-loki-distributor-http
  namespace: observatorium
spec:
  ports:
  - name: metrics
    port: 3100
    targetPort: 3100
  selector:
    app.kubernetes.io/component: distributor
    app.kubernetes.io/instance: observatorium-xyz
    app.kubernetes.io/name: loki
    app.kubernetes.io/part-of: observatorium
