apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: query-frontend
    app.kubernetes.io/instance: observatorium-xyz
    app.kubernetes.io/name: loki
    app.kubernetes.io/part-of: observatorium
    app.kubernetes.io/version: 1.6.1
  name: observatorium-xyz-loki-query-frontend-grpc
  namespace: observatorium
spec:
  clusterIP: None
  ports:
  - name: grcp
    port: 9095
    targetPort: 9095
  selector:
    app.kubernetes.io/component: query-frontend
    app.kubernetes.io/instance: observatorium-xyz
    app.kubernetes.io/name: loki
    app.kubernetes.io/part-of: observatorium
