apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: query-cache
    app.kubernetes.io/instance: observatorium-xyz
    app.kubernetes.io/name: cortex-query-frontend
    app.kubernetes.io/part-of: observatorium
    app.kubernetes.io/version: master-fdcd992f
  name: observatorium-xyz-cortex-query-frontend
  namespace: observatorium
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: query-cache
      app.kubernetes.io/instance: observatorium-xyz
      app.kubernetes.io/name: cortex-query-frontend
      app.kubernetes.io/part-of: observatorium
  template:
    metadata:
      labels:
        app.kubernetes.io/component: query-cache
        app.kubernetes.io/instance: observatorium-xyz
        app.kubernetes.io/name: cortex-query-frontend
        app.kubernetes.io/part-of: observatorium
        app.kubernetes.io/version: master-fdcd992f
    spec:
      containers:
      - args:
        - -log.level=debug
        - -config.file=/etc/cache-config/config.yaml
        - -querier.max-retries-per-request=0
        - -frontend.downstream-url=http://observatorium-xyz-thanos-query.observatorium.svc.cluster.local.:9090
        image: quay.io/cortexproject/cortex:master-fdcd992f
        name: cortex-query-frontend
        ports:
        - containerPort: 9090
          name: http
        volumeMounts:
        - mountPath: /etc/cache-config/
          name: query-cache-config
          readOnly: false
      volumes:
      - configMap:
          name: observatorium-xyz-cortex-query-frontend
        name: query-cache-config
