apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: object-store-gateway
    app.kubernetes.io/instance: observatorium-xyz
    app.kubernetes.io/name: thanos-store
    app.kubernetes.io/part-of: observatorium
    app.kubernetes.io/version: v0.16.0
    store.observatorium.io/shard: shard-0
  name: observatorium-xyz-thanos-store-shard-0
  namespace: observatorium
spec:
  clusterIP: None
  ports:
  - name: grpc
    port: 10901
    targetPort: grpc
  - name: http
    port: 10902
    targetPort: http
  selector:
    app.kubernetes.io/component: object-store-gateway
    app.kubernetes.io/instance: observatorium-xyz
    app.kubernetes.io/name: thanos-store
    app.kubernetes.io/part-of: observatorium
    store.observatorium.io/shard: shard-0
