apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: database-compactor
    app.kubernetes.io/instance: observatorium-xyz
    app.kubernetes.io/name: thanos-compact
    app.kubernetes.io/part-of: observatorium
    app.kubernetes.io/version: master-2020-08-12-70f89d83
  name: observatorium-xyz-thanos-compact
  namespace: observatorium
spec:
  ports:
  - name: http
    port: 10902
    targetPort: http
  selector:
    app.kubernetes.io/component: database-compactor
    app.kubernetes.io/instance: observatorium-xyz
    app.kubernetes.io/name: thanos-compact
    app.kubernetes.io/part-of: observatorium
