apiVersion: apps/v1
kind: Deployment
metadata:
  name: observatorium-xyz-observatorium-up
  namespace: observatorium
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: blackbox-prober
      app.kubernetes.io/instance: observatorium-xyz
      app.kubernetes.io/name: observatorium-up
      app.kubernetes.io/part-of: observatorium
  template:
    metadata:
      labels:
        app.kubernetes.io/component: blackbox-prober
        app.kubernetes.io/instance: observatorium-xyz
        app.kubernetes.io/name: observatorium-up
        app.kubernetes.io/part-of: observatorium
        app.kubernetes.io/version: master-2020-06-03-8a20b4e
    spec:
      containers:
      - args:
        - --duration=0
        - --log.level=debug
        - --endpoint-type=metrics
        - --endpoint-read=http://observatorium-xyz-observatorium-api.observatorium.svc.cluster.local:8080/api/metrics/v1/test/api/v1/query
        - --endpoint-write=http://observatorium-xyz-observatorium-api.observatorium.svc.cluster.local:8080/api/metrics/v1/test/api/v1/receive
        image: quay.io/observatorium/up:master-2020-06-03-8a20b4e
        name: observatorium-up
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits: {}
          requests: {}
        volumeMounts: []
      volumes: []
