apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rate-limiter
    app.kubernetes.io/instance: observatorium-xyz
    app.kubernetes.io/name: gubernator
    app.kubernetes.io/part-of: observatorium
    app.kubernetes.io/version: 1.0.0-rc.1
  name: observatorium-xyz-gubernator
  namespace: observatorium
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: observatorium-xyz-gubernator
subjects:
- kind: ServiceAccount
  name: observatorium-xyz-gubernator
  namespace: observatorium
