apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: query-cache
    app.kubernetes.io/instance: observatorium-xyz
    app.kubernetes.io/name: thanos-query-frontend
    app.kubernetes.io/part-of: observatorium
    app.kubernetes.io/version: v0.16.0
  name: observatorium-xyz-thanos-query-frontend
  namespace: observatorium
spec:
  ports:
  - name: http
    port: 9090
    targetPort: http
  selector:
    app.kubernetes.io/component: query-cache
    app.kubernetes.io/instance: observatorium-xyz
    app.kubernetes.io/name: thanos-query-frontend
    app.kubernetes.io/part-of: observatorium
