apiVersion: apps/v1
kind: Deployment
metadata:
  name: observatorium-operator
  labels:
    app.kubernetes.io/component: observatorium-operator
    app.kubernetes.io/name: observatorium-operator
    app.kubernetes.io/part-of: observatorium
    control-plane: observatorium-operator
spec:
  selector:
    matchLabels:
      control-plane: observatorium-operator
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: observatorium-operator
    spec:
      containers:
      - name: observatorium-operator
        image: quay.io/observatorium/observatorium-operator:latest
        imagePullPolicy: IfNotPresent
        args:
          - "--log-level=debug"
        resources:
          limits:
            cpu: 100m
            memory: 600Mi
          requests:
            cpu: 100m
            memory: 600Mi
      terminationGracePeriodSeconds: 10
