apiVersion: v1
data:
  config.yaml: |-
    "analytics":
      "reporting_enabled": false
    "chunk_store_config":
      "chunk_cache_config":
        "embedded_cache":
          "enabled": true
          "max_size_mb": 500
    "common":
      "compactor_grpc_address": "observatorium-xyz-loki-compactor.observatorium.svc.cluster.local:9095"
      "ring":
        "kvstore":
          "store": "memberlist"
    "compactor":
      "compaction_interval": "2h"
      "shared_store": "s3"
      "working_directory": "/data/loki/compactor"
    "distributor":
      "ring":
        "kvstore":
          "store": "memberlist"
    "frontend":
      "compress_responses": true
      "log_queries_longer_than": "5s"
      "scheduler_address": "observatorium-xyz-loki-query-scheduler-headless.observatorium.svc.cluster.local:9095"
      "tail_proxy_url": "observatorium-xyz-loki-querier.observatorium.svc.cluster.local:3100"
    "frontend_worker":
      "grpc_client_config":
        "max_send_msg_size": 104857600
      "match_max_concurrent": true
      "scheduler_address": "observatorium-xyz-loki-query-scheduler-headless.observatorium.svc.cluster.local:9095"
    "ingester":
      "chunk_block_size": 262144
      "chunk_encoding": "snappy"
      "chunk_idle_period": "1h"
      "chunk_retain_period": "5m"
      "chunk_target_size": 2097152
      "lifecycler":
        "heartbeat_period": "5s"
        "interface_names":
        - "eth0"
        "join_after": "30s"
        "num_tokens": 512
        "ring":
          "heartbeat_timeout": "1m"
          "kvstore":
            "store": "memberlist"
          "replication_factor": ${LOKI_REPLICATION_FACTOR}
      "max_transfer_retries": 0
      "wal":
        "dir": "/data/loki/wal"
        "enabled": true
        "replay_memory_ceiling": "100MB"
    "ingester_client":
      "grpc_client_config":
        "max_recv_msg_size": 67108864
      "remote_timeout": "1s"
    "limits_config":
      "cardinality_limit": 100000
      "creation_grace_period": "10m"
      "enforce_metric_name": false
      "ingestion_burst_size_mb": 20
      "ingestion_rate_mb": 10
      "ingestion_rate_strategy": "global"
      "max_cache_freshness_per_query": "10m"
      "max_chunks_per_query": 2000000
      "max_entries_limit_per_query": 5000
      "max_global_streams_per_user": 10000
      "max_label_name_length": 1024
      "max_label_names_per_series": 30
      "max_label_value_length": 2048
      "max_line_size": 256000
      "max_query_length": "721h"
      "max_query_parallelism": 16
      "max_query_series": 500
      "max_streams_per_user": 0
      "per_stream_rate_limit": "3MB"
      "per_stream_rate_limit_burst": "15MB"
      "reject_old_samples": true
      "reject_old_samples_max_age": "24h"
      "split_queries_by_interval": "30m"
    "memberlist":
      "abort_if_cluster_join_fails": false
      "bind_port": 7946
      "join_members":
      - "observatorium-xyz-loki-gossip-ring.observatorium.svc.cluster.local:7946"
      "max_join_backoff": "1m"
      "max_join_retries": 10
      "min_join_backoff": "1s"
    "querier":
      "max_concurrent": 2
      "query_ingesters_within": "2h"
    "query_range":
      "align_queries_with_step": true
      "cache_results": true
      "max_retries": 5
      "results_cache":
        "cache":
          "embedded_cache":
            "enabled": true
            "max_size_mb": 500
    "query_scheduler":
      "max_outstanding_requests_per_tenant": 256
    "ruler":
      "enable_api": true
      "enable_sharding": true
      "ring":
        "kvstore":
          "store": "memberlist"
      "rule_path": "/data"
      "storage":
        "type": "s3"
      "wal":
        "dir": "/data/loki/wal"
    "schema_config":
      "configs":
      - "from": "2020-10-01"
        "index":
          "period": "24h"
          "prefix": "loki_index_"
        "object_store": "s3"
        "schema": "v11"
        "store": "boltdb-shipper"
    "server":
      "graceful_shutdown_timeout": "5s"
      "grpc_server_max_concurrent_streams": 1000
      "grpc_server_max_recv_msg_size": 104857600
      "grpc_server_max_send_msg_size": 104857600
      "grpc_server_min_time_between_pings": "10s"
      "grpc_server_ping_without_stream_allowed": true
      "http_listen_port": 3100
      "http_server_idle_timeout": "120s"
      "http_server_write_timeout": "1m"
    "storage_config":
      "boltdb_shipper":
        "active_index_directory": "/data/loki/index"
        "cache_location": "/data/loki/index_cache"
        "index_gateway_client":
          "server_address": "observatorium-xyz-loki-index-gateway.observatorium.svc.cluster.local:9095"
        "shared_store": "s3"
  overrides.yaml: '{}'
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: observatorium-xyz
    app.kubernetes.io/name: loki
    app.kubernetes.io/part-of: observatorium
    app.kubernetes.io/version: 2.7.2
  name: observatorium-xyz-loki
  namespace: observatorium
