apiVersion: core.observatorium.io/v1alpha1
kind: Observatorium
metadata:
  labels:
    app.kubernetes.io/component: observatorium-cr
    app.kubernetes.io/instance: observatorium-xyz
    app.kubernetes.io/name: observatorium-cr
    app.kubernetes.io/part-of: observatorium
  name: observatorium-xyz
spec:
  api:
    image: quay.io/observatorium/observatorium:master-2020-05-11-v0.1.1-35-g3c24d9b
    version: master-2020-05-11-v0.1.1-35-g3c24d9b
  apiQuery:
    image: quay.io/thanos/thanos:v0.12.0-rc.1
    version: v0.12.0-rc.1
  compact:
    image: quay.io/thanos/thanos:v0.12.0-rc.1
    retentionResolution1h: 1s
    retentionResolution5m: 1s
    retentionResolutionRaw: 14d
    version: v0.12.0-rc.1
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
  hashrings:
    - hashring: default
      tenants: []
  objectStorageConfig:
    key: thanos.yaml
    name: thanos-objectstorage
  query:
    image: quay.io/thanos/thanos:v0.12.0-rc.1
    version: v0.12.0-rc.1
  queryCache:
    image: quay.io/cortexproject/cortex:master-fdcd992f
    replicas: 1
    version: master-fdcd992f
  receivers:
    image: quay.io/thanos/thanos:v0.12.0-rc.1
    version: v0.12.0-rc.1
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
  rule:
    image: quay.io/thanos/thanos:v0.12.0-rc.1
    version: v0.12.0-rc.1
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
  store:
    cache:
      exporterImage: prom/memcached-exporter:v0.6.0
      exporterVersion: v0.6.0
      image: docker.io/memcached:1.6.3-alpine
      memoryLimitMb: 1024
      replicas: 1
      version: 1.6.3-alpine
    image: quay.io/thanos/thanos:v0.12.0-rc.1
    shards: 1
    version: v0.12.0-rc.1
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
  thanosReceiveController:
    image: quay.io/observatorium/thanos-receive-controller:master-2020-02-06-b66e0c8
    version: master-2020-02-06-b66e0c8
