apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  labels:
    app.kubernetes.io/component: test-oidc
    app.kubernetes.io/instance: observatorium-xyz
    app.kubernetes.io/name: otelcol
    app.kubernetes.io/part-of: observatorium
  name: observatorium-xyz-jaeger-test-oidc
  namespace: observatorium
spec:
  strategy: allinone
  ui:
    options:
      dependencies:
        menuEnabled: false
      menu:
      - items:
        - label: Documentation
          url: https://access.redhat.com/documentation/en-us/openshift_container_platform/4.9/html/distributed_tracing/index
        label: About
      - anchorTarget: _self
        label: Log Out
        url: ./login
