apiVersion: v1
data:
  rbac.yaml: |-
    "roleBindings":
    - "name": "test"
      "roles":
      - "read-write"
      "subjects":
      - "kind": "user"
        "name": "user"
    "roles":
    - "name": "read-write"
      "permissions":
      - "read"
      - "write"
      "resources":
      - "logs"
      - "metrics"
      "tenants":
      - "test-oidc"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: observatorium-xyz
    app.kubernetes.io/name: observatorium-api
    app.kubernetes.io/part-of: observatorium
    app.kubernetes.io/version: master-2020-11-02-v0.1.1-192-ge324057
  name: observatorium-xyz-observatorium-api
  namespace: observatorium
