apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: kubernetes-controller
    app.kubernetes.io/instance: observatorium-xyz
    app.kubernetes.io/name: thanos-receive-controller
    app.kubernetes.io/part-of: observatorium
    app.kubernetes.io/version: master-2020-02-06-b66e0c8
  name: observatorium-xyz-thanos-receive-controller
  namespace: observatorium
